[workspace]
channels = ["https://conda.modular.com/max-nightly", "conda-forge"]
name = "pendulum"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]
update = "sh update.sh"

[dependencies]
mojo = ">=25.5.0.dev2025072805"
# max = ">=25.5.0.dev2025071505"
max = "*"
python = ">=3.10,<3.13"
pip = ">=24.3.1"
